# agent_generated/_registry.py
"""
Unified discovery layer for agent-generated capabilities (losses today; models /
data-analysis tools / feature extractors in future).

A "capability" is anything the agent generates at runtime that subsequent
iterations may want to discover and reuse. The first concrete type is a custom
loss function (see ``agent_generated/_loss_loader.py``). The registry is
type-agnostic by design: each entry carries a ``capability_type`` field, and
callers filter by it.

Storage: a flat JSON array at ``agent_generated/_capability_index.json``.
Reading it requires **only** ``json.load`` — no Python import of the plugin
module is needed, so a future CLI (e.g. ``siderius capabilities list``) can
inspect the registry even when individual plugin files are broken.

Writes are atomic via tmp-file rename — concurrent ``register()`` calls from
two processes do not corrupt the JSON. The rename pattern matches the
``_snapshot_task_config`` helper landed in ``enable_global_task_config`` T1b.

See ``docs/design/enable_loss_inventory.md`` § Commit L1 for the full design.
"""

from __future__ import annotations

import json
import os
import tempfile
from typing import Literal

from pydantic import BaseModel, Field

# Repo-relative default path. Resolved at call time (not import time) so a
# test that monkeypatches ``os.getcwd`` or chdirs into a fixture dir sees the
# updated cwd.
_DEFAULT_INDEX_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "_capability_index.json",
)

# Supported capability types. Loss is the first concrete type. ``model`` is
# reserved for a future opt-in registration of agent-generated model plugins;
# ``tool`` is reserved for data-analysis / feature-extractor plugins that
# future modules may introduce.
CapabilityType = Literal["loss", "model", "tool"]


class CapabilityMetadata(BaseModel):
    """One row in the capability registry.

    Carried as a Pydantic model so the JSON shape is validated on every
    ``register()`` call — a typo'd field name (e.g. ``filepath`` instead of
    ``file_path``) raises a ``ValidationError`` at write time, not at read
    time when downstream code tries to load the missing key.

    Fields:
        name: The plugin's ``PLUGIN_*_TYPE`` key (e.g. ``"snr_weighted_mse"``).
            Must be unique within a given ``capability_type``.
        capability_type: One of ``"loss"``, ``"model"``, ``"tool"``.
        file_path: Absolute path to the plugin's ``.py`` file.
        created_at: ISO-8601 UTC timestamp captured at registration time.
        source_iteration: Optional iteration label (e.g. ``"iter_014"``) the
            plugin was generated by. ``None`` for capabilities not produced
            inside the agent loop (test fixtures, hand-written plugins).
        description: One-line plain-English summary. Rendered into the
            proposer's ``{AVAILABLE_LOSSES}`` placeholder (L5).
    """

    name: str = Field(min_length=1, description="Plugin's unique identifier key.")
    capability_type: CapabilityType = Field(description="Category of capability.")
    file_path: str = Field(min_length=1, description="Absolute path to the .py file.")
    created_at: str = Field(min_length=1, description="ISO-8601 UTC timestamp.")
    source_iteration: str | None = Field(
        default=None,
        description="Iteration label the plugin was generated by; None for non-agent sources.",
    )
    description: str = Field(default="", description="One-line plain-English summary.")


class CapabilityRegistry:
    """Persistent registry of agent-generated capabilities.

    Backed by ``agent_generated/_capability_index.json``. Each instance reads
    that file on demand (no in-memory cache) so concurrent processes see
    each other's writes via the filesystem.

    The registry is small (one row per ever-generated plugin, typically tens
    to low hundreds) so a full re-read per call is cheap. If profiling later
    shows this as a hot path, the caller can drop in a session-level cache.
    """

    def __init__(self, index_path: str | None = None) -> None:
        """Initialize with the index file path (defaults to the canonical one).

        Args:
            index_path: Optional override. Defaults to
                ``agent_generated/_capability_index.json``. Tests pass a
                ``tmp_path`` location to avoid contaminating the canonical
                index.
        """
        self._index_path = index_path or _DEFAULT_INDEX_PATH

    @property
    def index_path(self) -> str:
        """Absolute path to the backing JSON file."""
        return self._index_path

    def _read_raw(self) -> list[dict]:
        """Return the raw list of dicts from the index file.

        Returns ``[]`` when the file does not exist (first-run behavior). When
        the file exists but is empty or contains ``null``, returns ``[]`` —
        either case is treated as "no capabilities yet" rather than a hard
        error so a freshly-created index doesn't need special-casing at every
        caller.
        """
        if not os.path.isfile(self._index_path):
            return []
        with open(self._index_path, encoding="utf-8") as f:
            raw = json.load(f)
        if raw is None:
            return []
        if not isinstance(raw, list):
            raise ValueError(
                f"{self._index_path}: expected a JSON array at top level, "
                f"got {type(raw).__name__}. The registry index has been "
                f"corrupted — restore from git or delete the file to reset."
            )
        return raw

    def _write_raw(self, entries: list[dict]) -> None:
        """Atomically write the list of entries to the index file.

        Uses tmp-file-then-rename so a concurrent reader never sees a
        partially-written JSON file. Same atomicity pattern as the T1b
        ``_snapshot_task_config`` helper.
        """
        os.makedirs(os.path.dirname(self._index_path) or ".", exist_ok=True)
        # delete=False so we keep ownership of the path past the with-block;
        # we explicitly close + rename + cleanup ourselves.
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=os.path.dirname(self._index_path),
            prefix=".capability_index_",
            suffix=".tmp",
            delete=False,
        ) as tmp:
            json.dump(entries, tmp, indent=2, sort_keys=False)
            tmp.write("\n")
            tmp_path = tmp.name
        os.replace(tmp_path, self._index_path)

    def list(self, capability_type: CapabilityType | None = None) -> list[CapabilityMetadata]:
        """Return all registered capabilities, optionally filtered by type.

        Args:
            capability_type: If provided, only entries with this type are
                returned. ``None`` (default) returns everything.

        Returns:
            List of validated ``CapabilityMetadata`` objects, in insertion
            order. Empty list when the registry is empty or no entries match
            the filter.

        Raises:
            pydantic.ValidationError: Propagated if any row in the index
                violates the schema. This protects callers from silent
                corruption — a hand-edited registry with a malformed row
                surfaces at list time, not when the row is later accessed.
        """
        rows = self._read_raw()
        out: list[CapabilityMetadata] = []
        for row in rows:
            meta = CapabilityMetadata.model_validate(row)
            if capability_type is None or meta.capability_type == capability_type:
                out.append(meta)
        return out

    def exists(self, name: str, capability_type: CapabilityType) -> bool:
        """Return True iff a capability with this (name, capability_type) is registered.

        Used by the implementor's L4 short-circuit path: when the proposer
        asks for a loss the registry already has, the implementor skips the
        LLM code-generation call entirely and reuses the existing plugin.
        """
        return any(meta.name == name for meta in self.list(capability_type=capability_type))

    def register(self, metadata: CapabilityMetadata) -> None:
        """Append a new capability to the registry.

        Rejects duplicates of the (name, capability_type) tuple — if a caller
        re-registers an existing plugin, that's a code bug (the L4
        short-circuit should have caught the re-use). Raising here makes the
        bug audible at write time.

        Args:
            metadata: Validated CapabilityMetadata instance.

        Raises:
            ValueError: If a capability with the same (name, capability_type)
                already exists in the registry.
        """
        if self.exists(metadata.name, metadata.capability_type):
            raise ValueError(
                f"Capability already registered: name={metadata.name!r}, "
                f"capability_type={metadata.capability_type!r}. The implementor "
                f"should short-circuit on registry-hit before calling register() — "
                f"this exception means the short-circuit was missed."
            )
        rows = self._read_raw()
        rows.append(metadata.model_dump())
        self._write_raw(rows)
