"""Mechanical rescue evidence for an automatic compaction over stale memory.

When Claude Code compacts automatically, blocking is not an option: the
session has already run out of room, so a refusal fails the current
request and leaves no way forward. But compacting over a stale handoff
loses state silently, which is how a whole implementation session ends up
unrecoverable.

This module is the middle path. It writes down what a shell process can
know **for certain** — git state, the handoff's own recorded values, and
which freshness conditions failed — and says plainly that the semantic
handoff may be wrong.

**What it must never do is summarise.** No scientific decisions, no
architecture, no test diagnosis, no implementation intent, no "next
steps". A hook cannot author semantic memory; text that looks like memory
but was generated by a script is exactly the failure mode the whole
continuity system exists to prevent — plausible prose nobody verified.
Everything here is either copied verbatim from the handoff or read
directly from git.

The snapshot lives under the gitignored runtime directory and is
excluded from the working-tree fingerprint, so writing it can never
invalidate the handoff it is reporting on.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from tools.claude_hooks.context_state import (
    FIELD_BINDING_DOCS,
    FIELD_FINGERPRINT,
    FIELD_HEAD,
    ContinuityError,
    _git,
    atomic_write,
    branch_name,
    head_sha,
    read_field,
    read_pr_identity,
    rescue_path,
    semantic_handoff,
    working_tree_fingerprint,
)

#: Bumped when the fields below change meaning, so a reader can tell an
#: old snapshot from a new one instead of guessing.
SCHEMA = "siderius.context_rescue/1"

RECOVERY_INSTRUCTION = """\
The semantic handoff may be stale.
This snapshot is mechanical evidence only.

Before editing after compaction:
  inspect repository/git/process truth;
  re-read the active design;
  re-read current working-tree diff;
  inspect transcript tail if available;
  reconcile before continuing.

Do not infer unfinished implementation semantics from this snapshot.
"""

_MAX_LIST = 40
_MAX_COMMITS = 15


def _fence(title: str, lines: list[str]) -> list[str]:
    return [f"### {title}", "", "```text", *(lines or ["(none)"]), "```", ""]


def render(
    root: Path,
    *,
    event: dict | None = None,
    handoff_text: str | None = None,
    problems: list[str] | None = None,
) -> str:
    """Render the snapshot. Mechanical facts only.

    ``handoff_text`` is optional because the handoff may be missing
    entirely — that is itself a fact worth recording rather than a reason
    to skip the snapshot.
    """
    event = event or {}
    problems = problems or []

    status = [ln for ln in _git(root, "status", "--short").splitlines() if ln.strip()]
    names = [ln for ln in _git(root, "diff", "--name-only", "HEAD").splitlines() if ln.strip()]
    stat = [ln for ln in _git(root, "diff", "--stat", "HEAD").splitlines() if ln.strip()]
    commits = [
        ln
        for ln in _git(root, "log", "--oneline", "--decorate", f"-{_MAX_COMMITS}").splitlines()
        if ln.strip()
    ]

    recorded_head = recorded_fp = "(no handoff)"
    project = design = binding = "(not parsable from the handoff)"
    if handoff_text is not None:
        try:
            handoff = semantic_handoff(handoff_text)
        except ContinuityError:
            handoff = handoff_text  # malformed markers — still worth scanning
        identity = read_pr_identity(handoff)
        recorded_head = read_field(handoff, FIELD_HEAD) or "(absent)"
        recorded_fp = read_field(handoff, FIELD_FINGERPRINT) or "(absent)"
        project = identity.project or "(absent)"
        design = identity.primary_design or "(absent)"
        binding = read_field(handoff, FIELD_BINDING_DOCS) or "(absent)"

    lines: list[str] = [
        "# Automatic-compaction rescue snapshot",
        "",
        "> Written mechanically by `tools/claude_hooks/rescue_snapshot.py`",
        "> during an AUTOMATIC compaction whose semantic handoff was not",
        "> current. It contains no summary and no interpretation.",
        "",
        "```text",
        f"schema               {SCHEMA}",
        f"generated_at_utc     {datetime.now(UTC).isoformat(timespec='seconds')}",
        "trigger              auto",
        f"session_id           {event.get('session_id') or '(not supplied)'}",
        f"transcript_path      {event.get('transcript_path') or '(not supplied)'}",
        f"repository_root      {root}",
        f"branch               {branch_name(root)}",
        f"head_sha             {head_sha(root)}",
        f"working_fingerprint  {working_tree_fingerprint(root)}",
        f"changed_file_count   {len(status)}",
        "```",
        "",
        "### Active PR, as recorded by the handoff (verbatim, unverified)",
        "",
        "```text",
        f"PROJECT / PR         {project}",
        f"PRIMARY DESIGN DOC   {design}",
        f"BINDING DOCS         {binding}",
        "```",
        "",
        "### Why the handoff was not current",
        "",
        "```text",
        f"handoff HEAD         {recorded_head}",
        f"handoff fingerprint  {recorded_fp}",
        "```",
        "",
    ]
    lines += _fence("Freshness failures", [f"- {p}" for p in problems])
    lines += _fence("git status --short", status[:_MAX_LIST])
    lines += _fence("changed files vs HEAD", names[:_MAX_LIST])
    lines += _fence("diff --stat vs HEAD", stat[-_MAX_LIST:])
    lines += _fence("recent commits", commits)
    lines += ["## Recovery instruction", "", "```text", RECOVERY_INSTRUCTION.rstrip(), "```", ""]
    return "\n".join(lines)


def write(
    root: Path,
    *,
    event: dict | None = None,
    handoff_text: str | None = None,
    problems: list[str] | None = None,
) -> Path:
    """Render and atomically write the snapshot. Returns its path."""
    path = rescue_path(root)
    atomic_write(path, render(root, event=event, handoff_text=handoff_text, problems=problems))
    return path
