"""C12-P / F-12e-G1 — the GENERATED PLUGIN declares nothing the baseline said.

THE ESCAPED CLASS, NAMED
------------------------
*The framework authors a value into an artifact that later becomes the
model's own declaration.*

B11's standing census
(``tests/unit/guardrails/test_c12p_b11_segmentation_default_census.py``) is a
SOURCE-LEVEL scan for ``<mapping>.get("segmentation_size", <int literal>)``.
It cannot own this class, and the reason is structural rather than a matter of
tuning the regex: after the repair **there is no literal left in the source to
find**. The number's whole career was to be written into generated bytes. So
the only place the property can be asserted is the ARTIFACT — assemble a
plugin, execute it, register it exactly as production does, and ask the
production resolution chain what the model declares.

That chain, end to end, is what made a framework literal permanent::

    _assemble_plugin        writes `segmentation_size: int = Field(default=N)`
    register_model_in_memory  -> PLUGIN_CONFIG_REGISTRY
    get_config_class          -> the generated class
    estimator.resolve_model_field   reads its DECLARED default
    planning._resolve_declared_segmentation_size    -> that value, never None

Because a generated class ALWAYS declared a default, the middle link could
never return ``None`` for a plugin, and the task's named refusal
(``execute_tools/tidmad_data_path.py``: *"the framework has no vocabulary for
it, so it must be declared by the caller rather than guessed here"*) — which
F-C12P-B11-2's approved repair exists to keep reachable — was defeated from
OUTSIDE the tuner. The framework's own 40000 came back to it wearing the
task's clothes.

Measured harm, for a generated non-TIDMAD candidate:
``agent/skills/training_skill/estimator.py`` prices activations as
``batch_size * 256 * segmentation_size * 4``. Pets' 144 replaced by 40000 is a
278x VRAM over-estimate, so the capacity gate rejects a perfectly feasible
architecture and burns a tuner attempt — silently, with a plausible number.

WHY THE FIXTURES ARE HAND-WRITTEN
---------------------------------
Every expectation below is a hardcoded literal (``0``, ``None``, ``144``, the
exact emitted field line). Nothing is read back from the thing under test: an
assertion like ``emitted == Model.model_fields[...].default`` compares the
artifact to itself and passes for any value, which is precisely how a
recomputation defect survives a green suite.
"""

from __future__ import annotations

import importlib

import pytest

from agent.schemas.implementor import ImplementorInput

_impl = importlib.import_module("nodes.ml_model_implementor.ml_model_implementor")
#: The DOWNSTREAM consumer of the same construction rule. ``TestOne
#: ProbeConstructionAuthority`` asserts across both nodes on purpose: the
#: property is that exactly one authority exists, and a per-node test cannot
#: express it.
_val = importlib.import_module("nodes.ml_code_validator_agent.ml_code_validator_agent")
#: A tuner-private module. Tests are deliberately exempt from the node public
#: boundary rule (``tests/unit/nodes/test_node_public_boundary.py``) precisely
#: so a reachability test like this one can assert against the real consumer.
_planning = importlib.import_module("nodes.ml_hyperparameter_tune_agent.planning")

_FIELD = "segmentation_size"

#: A minimal but REAL architecture: the assembled plugin is EXECUTED — its
#: smoke test, its own generated pytest file and the registry all run against
#: it — so it must honour the default ``classifier`` contract
#: (``[B, T] int -> [B, 256, T] float``). It deliberately does not read
#: ``config.segmentation_size``, so the declared and undeclared cases differ in
#: exactly one thing.
#:
#: ``channels`` is declared ``ge=8`` so that a baseline asking for 2 is a
#: genuine constraint violation — that is what
#: ``test_a_real_schema_rejection_is_still_reported`` needs, and a ``ge=1``
#: here would make it pass vacuously.
_CODE = {
    "extra_imports": "",
    "config_fields_code": "    channels: int = Field(default=8, ge=8)",
    "config_validators_code": "",
    "init_body": (
        "        self.emb = nn.Embedding(256, config.channels)\n"
        "        self.out = nn.Conv1d(config.channels, 256, 1)"
    ),
    "forward_body": "        return self.out(self.emb(x.long()).transpose(1, 2))",
}


def _implementor_input(model_name: str, model_config: dict) -> ImplementorInput:
    """A Pets-shaped baseline: small, non-TIDMAD, and 1-D-geometry-free."""
    return ImplementorInput(
        model_name=model_name,
        model_description="C12-P F-12e-G1 fixture candidate.",
        mathematical_definition="Embedding(256, C) -> transpose -> Conv1d(C, 256, 1). Fixture.",
        baseline_config={
            "model_config": model_config,
            # NOTE: `train_config` deliberately carries no `segmentation_size`
            # either. `TrainConfig` (`ml_models/models_format_sandbox.py`)
            # declares no such field, so the implementor's old inner fallback
            # `train_cfg.get("segmentation_size", 40000)` was dead code whose
            # only reachable arm was the 40000.
            "train_config": {"batch_size": 4, "lr": 5e-4},
        },
    )


@pytest.fixture
def registered(tmp_path):
    """Assemble, execute and register a candidate the way production does.

    Yields a ``register(model_name, model_config) -> plugin_source`` callable.
    Registration mutates three module-level dicts, so every entry is removed
    afterwards — a leaked registration would make a LATER test's
    ``get_config_class`` resolve and silently change what it proves.
    """
    from ml_models.models_format_sandbox import PLUGIN_CONFIG_REGISTRY
    from ml_models.models_sandbox import MODEL_REGISTRY
    from ml_models.plugin_loader import PLUGIN_OUTPUT_TYPE_REGISTRY, register_model_in_memory

    created: list[str] = []

    def _register(model_name: str, model_config: dict) -> str:
        src = _impl._assemble_plugin(_implementor_input(model_name, model_config), _CODE)
        path = tmp_path / f"{model_name}.py"
        path.write_text(src, encoding="utf-8")
        assert register_model_in_memory(str(path)) == model_name, (
            "the assembled plugin did not load — this test proves nothing "
            "about declarations until it does"
        )
        created.append(model_name)
        return src

    try:
        yield _register
    finally:
        for name in created:
            MODEL_REGISTRY.pop(name, None)
            PLUGIN_CONFIG_REGISTRY.pop(name, None)
            PLUGIN_OUTPUT_TYPE_REGISTRY.pop(name, None)


def _resolution_chain(model_name: str) -> tuple[int, int | None]:
    """``(resolve_model_field, _resolve_declared_segmentation_size)``.

    The two production readers, asked in the order production asks them.
    ``safety_margin=0`` is the tuner's own "nothing declares this" sentinel.
    """
    from agent.skills.training_skill.estimator import resolve_model_field

    return (
        resolve_model_field(model_name, {}, _FIELD, safety_margin=0),
        _planning._resolve_declared_segmentation_size(model_name, {}),
    )


class TestAnUndeclaredSizeStaysUndeclared:
    def test_an_omitted_size_is_not_authored_into_the_generated_declaration(self, registered):
        """DEFECT THIS TEST ALONE CATCHES

            ``_assemble_plugin`` writing a framework-chosen number into the
            generated class's own default when the baseline declared none —
            after which every downstream reader is looking at a declaration
            that no proposer, plan or task ever made. A source-level census
            structurally cannot see this, because the number ends up in
            generated bytes, not in repository source.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            Someone restores ``.get(_FIELD, 40000)`` (or any other literal) at
            the assembly site. The emitted line then reads
            ``Field(default=40000, ge=1)`` instead of ``Field(ge=1)`` and the
            first assertion names it; the resolution chain then returns 40000
            instead of ``0``/``None`` and the remaining two name it again, at
            the exact two call sites that made the number consequential.
        """
        source = registered("c12p_f12e_g1_omitted_v1", {"channels": 8})

        emitted = [ln for ln in source.splitlines() if ln.strip().startswith(f"{_FIELD}:")]
        assert emitted == ["    segmentation_size: int = Field(ge=1)"], (
            "the generated plugin declares a segmentation_size the baseline "
            f"never stated: {emitted}"
        )

        resolved, declared = _resolution_chain("c12p_f12e_g1_omitted_v1")
        assert resolved == 0, (
            "`resolve_model_field` found a declared default on a class whose "
            "baseline declared none — the framework's literal is being read "
            "back as the model's own value"
        )
        assert declared is None, (
            "the tuner resolved a segmentation size for a candidate nothing "
            "declared one for; the task's named refusal is unreachable again"
        )

    def test_the_field_still_exists_on_the_generated_class(self, registered):
        """DEFECT THIS TEST ALONE CATCHES

            "Don't author a value" implemented as "drop the field". Two
            production readers access it as an ATTRIBUTE —
            ``agent/skills/training_skill/train_engine_sandbox.py`` and
            ``agent/skills/inference_skill/inference_single.py`` — and
            ``_TEMPLATE_CONFIG_FIELDS`` still forbids the LLM to declare it,
            so a removed field would leave it declared by nobody at all.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The template stops emitting the field and ``model_fields`` no
            longer contains it.
        """
        from ml_models.models_format_sandbox import get_config_class

        registered("c12p_f12e_g1_exists_v1", {"channels": 8})
        config_cls = get_config_class("c12p_f12e_g1_exists_v1")
        assert config_cls is not None
        assert _FIELD in config_cls.model_fields, (
            "the generated class no longer declares `segmentation_size` at "
            "all; train_engine_sandbox and inference_single read it as an "
            "attribute"
        )
        assert config_cls.model_fields[_FIELD].is_required(), (
            "an undeclared size must be REQUIRED, not optional-with-a-value: "
            "any usable default is a number the framework chose"
        )


class TestADeclaredSizeIsCarriedExactly:
    def test_a_declared_size_reaches_the_class_default_and_both_readers(self, registered):
        """DEFECT THIS TEST ALONE CATCHES

            The repair over-reaching into a blanket removal — emitting a
            required field even when the baseline DID declare a size. That
            would break every real candidate (built-ins and proposals alike)
            while the test above stayed green, because that test only ever
            looks at the omitted case.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The emitted line loses its ``default=144`` and the chain returns
            ``0``/``None`` for a candidate that plainly stated 144.

        144 is Pets' scale, hardcoded here on purpose: it is nothing like
        TIDMAD's 40000, so a fallback re-entering anywhere in the chain shows
        up as a different number rather than a coincidence.
        """
        source = registered("c12p_f12e_g1_declared_v1", {"channels": 8, _FIELD: 144})

        emitted = [ln for ln in source.splitlines() if ln.strip().startswith(f"{_FIELD}:")]
        assert emitted == ["    segmentation_size: int = Field(default=144, ge=1)"], emitted

        assert _resolution_chain("c12p_f12e_g1_declared_v1") == (144, 144)


class TestTheRetiredExemptionsPremise:
    def test_get_config_class_resolves_a_generated_name_once_it_is_registered(self, registered):
        """The premise of the census exemption this PR RETIRES, asserted as
        the expiring thing it always was.

        The B11 census exempted ``ml_model_implementor.py`` on the ground that
        ``get_config_class`` "returns ``None`` there by construction", so the
        literal overrode no declaration. That is true only BEFORE
        ``_assemble_plugin`` runs — and ``_assemble_plugin`` is the act that
        ends it. The exemption licensed the very step that falsified it.

        Its paired reachability test asserted the premise on a model name for
        which nothing had ever been assembled
        (``c12p_b11_a_model_that_does_not_exist_v1``): an input that could
        never falsify it, so the guard was green for the wrong reason.

        DEFECT THIS TEST ALONE CATCHES

            The exemption being reinstated on that same reasoning. This states
            both halves of the transition on ONE name, so "no config class can
            exist here" is visibly false for the module that generates them.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            Either half moves: a name resolves before anything was assembled
            for it, or registration stops making a generated class visible to
            ``get_config_class`` (which would silently return the resolution
            chain to its safety margin for every plugin).
        """
        from ml_models.models_format_sandbox import get_config_class

        name = "c12p_f12e_g1_premise_v1"
        assert get_config_class(name) is None, (
            "a generated name resolved before anything was assembled for it"
        )

        registered(name, {"channels": 8, _FIELD: 144})

        assert get_config_class(name) is not None, (
            "registration did not make the generated config class visible; "
            "the census exemption's premise ('no config class can exist "
            "here') would then be accidentally true for the wrong reason"
        )


class TestTheImplementorCanStillEmitSuchACandidate:
    """The repair's own blast radius, which the brief for it did not name.

    Emitting a REQUIRED field ends "construct with defaults" for an
    undeclared candidate — and THREE sites in the implementor did exactly
    that: ``_smoke_test_plugin`` (validation check 4),
    ``_check_baseline_schema_compatibility`` (check 5) and the ``TEST_TEMPLATE``
    body that ``ml_code_validator_agent`` runs under pytest downstream.

    Left alone, the repair would have traded a 278x mis-price for a hard
    stop: every candidate whose baseline omits the key would fail its own
    validation, exhaust the repair loop against an instruction it is
    forbidden to follow (``_TEMPLATE_CONFIG_FIELDS`` bars the LLM from
    touching ``segmentation_size``), and never be implemented at all.
    """

    def test_the_self_checks_accept_a_candidate_that_declared_no_size(self, tmp_path):
        """DEFECT THIS TEST ALONE CATCHES

            The two in-node self-checks constructing the config class with no
            arguments. Both return a human-readable STRING on failure rather
            than raising, so the failure is invisible to every other test
            here — the plugin still assembles, still declares correctly, and
            still resolves correctly; it simply never gets past check 4.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            ``_smoke_test_plugin`` returns
            ``"ValidationError: ... segmentation_size Field required"`` and
            the assertion prints it verbatim.
        """
        baseline = _implementor_input("c12p_f12e_g1_selfcheck_v1", {"channels": 8})
        src = _impl._assemble_plugin(baseline, _CODE)

        assert _impl._smoke_test_plugin(src, "c12p_f12e_g1_selfcheck_v1", None) is None, (
            "the implementor's own smoke test cannot construct the plugin it just assembled"
        )
        assert (
            _impl._check_baseline_schema_compatibility(
                src, "c12p_f12e_g1_selfcheck_v1", baseline.baseline_config
            )
            is None
        ), "the baseline self-check reports a field the baseline was never going to supply"

    def test_a_real_schema_rejection_is_still_reported(self, tmp_path):
        """DEFECT THIS TEST ALONE CATCHES

            The ``missing``-suppression above widening into a blanket
            ``except``. It exists to swallow exactly one unactionable error;
            if it swallowed a genuine one, the Phase-B.2a gate would go
            silent and the implementor would ship plugins whose schema
            rejects the proposer's own values — the 2026-04-16
            ``explore_novel_v1`` failure the gate was built for.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The helper returns ``None`` for a baseline that plainly violates
            a declared constraint, and this assertion says so.
        """
        # `channels` is declared `ge=8` by `_CODE`; the baseline asks for 2. It also omits
        # `segmentation_size`, so BOTH error classes are present at once --
        # which is the case the suppression must not collapse.
        baseline = _implementor_input("c12p_f12e_g1_realreject_v1", {"channels": 2})
        src = _impl._assemble_plugin(baseline, _CODE)

        err = _impl._check_baseline_schema_compatibility(
            src, "c12p_f12e_g1_realreject_v1", baseline.baseline_config
        )
        assert err is not None, (
            "a genuine constraint violation was suppressed along with the "
            "undeclared segmentation_size"
        )
        assert "channels" in err

    def test_the_generated_test_file_passes_for_an_undeclared_candidate(self, tmp_path):
        """DEFECT THIS TEST ALONE CATCHES

            ``TEST_TEMPLATE`` emitting ``PLUGIN_CONFIG_CLASS()`` for a plugin
            that cannot be constructed that way. This artifact leaves the
            node — ``ml_code_validator_agent`` runs pytest on it — so no
            in-node check sees the failure; the candidate is rejected one
            node downstream, with a validator error that names Pydantic
            rather than the cause.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The subprocess exits non-zero and its output is printed.
        """
        import subprocess
        import sys

        name = "c12p_f12e_g1_gentest_v1"
        (tmp_path / f"{name}.py").write_text(
            _impl._assemble_plugin(_implementor_input(name, {"channels": 8}), _CODE),
            encoding="utf-8",
        )
        (tmp_path / f"test_{name}.py").write_text(
            _impl._assemble_test(name, None, config_declares_segmentation_size=False),
            encoding="utf-8",
        )

        result = subprocess.run(
            [sys.executable, "-m", "pytest", f"test_{name}.py", "-q"],
            cwd=tmp_path,
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"{result.stdout}\n{result.stderr}"

    def test_a_declared_candidate_still_gets_the_shipped_construction_line(self):
        """DEFECT THIS TEST ALONE CATCHES

            The probe kwarg leaking into the normal path, which would change
            the emitted test bytes for every real candidate and silently
            override a declared geometry with 64 in the generated test.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The rendered line carries a ``segmentation_size=`` argument.
        """
        rendered = _impl._assemble_test("c12p_f12e_g1_declared_test_v1", None)
        assert "    config = PLUGIN_CONFIG_CLASS()\n" in rendered
        assert "PLUGIN_CONFIG_CLASS(segmentation_size" not in rendered


class TestThePydanticVocabularyTheSuppressionCouplesTo:
    """``_rejection_is_only_the_undeclared_segmentation_size`` reads Pydantic's
    error vocabulary directly — ``type == "missing"`` and a bare
    ``loc == ("segmentation_size",)``. That is a coupling to a third-party
    contract, and it should be visible to whoever next upgrades Pydantic.

    The coupling is SAFE by construction: every unrecognised shape makes the
    predicate return ``False``, i.e. "report this rejection". A vocabulary
    change therefore produces a false REJECTION — a loud, actionable repair
    message — never a silent pass. These tests pin the vocabulary so the
    upgrade is caught here rather than as a confusing implementor failure.
    """

    def test_a_missing_required_field_reports_type_missing_at_a_bare_loc(self):
        """DEFECT THIS TEST ALONE CATCHES

            A Pydantic upgrade renaming ``"missing"`` or nesting ``loc``.
            Nothing else in the suite asserts this vocabulary, and production
            would degrade quietly into "never suppress" — every undeclared
            candidate would then burn its whole repair budget on the
            unsatisfiable instruction the suppression exists to avoid.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The error ``type`` or ``loc`` assertion names the new shape, and
            the predicate assertion shows production no longer recognises it.
        """
        from pydantic import BaseModel, Field, ValidationError

        class _Probe(BaseModel):
            segmentation_size: int = Field(ge=1)

        with pytest.raises(ValidationError) as excinfo:
            _Probe()

        details = excinfo.value.errors()
        assert len(details) == 1
        assert details[0]["type"] == "missing"
        assert tuple(details[0]["loc"]) == ("segmentation_size",)

        # ...and production reads that shape correctly, asked through its own
        # entry point rather than by re-deriving the comparison here.
        assert _impl._rejection_is_only_the_undeclared_segmentation_size(excinfo.value, {}) is True

    def test_an_unrecognised_exception_shape_fails_CLOSED(self):
        """DEFECT THIS TEST ALONE CATCHES

            The predicate's fallbacks being flipped to ``True`` — "if I can't
            tell, assume it's the benign one". That is the difference between
            a suppression that hides exactly one unactionable error and one
            that silences the Phase-B.2a gate whenever it is confused.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            Any of these returns ``True``, meaning a rejection production
            could not classify would be discarded rather than reported.
        """

        class _ErrorsRaises(Exception):
            def errors(self):
                raise RuntimeError("errors() itself is broken")

        # not a Pydantic error at all
        assert (
            _impl._rejection_is_only_the_undeclared_segmentation_size(RuntimeError("x"), {})
            is False
        )
        # has errors(), but calling it blows up
        assert (
            _impl._rejection_is_only_the_undeclared_segmentation_size(_ErrorsRaises(), {}) is False
        )

    def test_the_baseline_having_stated_the_key_is_checked_before_the_vocabulary(self):
        """DEFECT THIS TEST ALONE CATCHES

            The predicate keying on the ERROR alone. A baseline that stated
            ``segmentation_size`` and had it rejected is a real schema
            conflict — the exact class Phase B.2a exists for — and it must
            never be suppressed just because the error mentions that field.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The assertion returns ``True`` for a baseline that plainly
            declared the key.
        """
        from pydantic import BaseModel, Field, ValidationError

        class _Probe(BaseModel):
            segmentation_size: int = Field(ge=1)

        with pytest.raises(ValidationError) as excinfo:
            _Probe()

        assert (
            _impl._rejection_is_only_the_undeclared_segmentation_size(
                excinfo.value, {"segmentation_size": 144}
            )
            is False
        )


class TestOneProbeConstructionAuthority:
    """The repair's second half: ONE owner for "how does a probe construct
    this config class", consumed by both nodes that construct one.

    The first half of F-12e-G1 (above) removed the invented default and so
    made *a config class with a REQUIRED field* a legitimate candidate state
    for the first time. ``ml_model_implementor`` taught its own self-check to
    construct such a class; ``ml_code_validator_agent``'s check 6 still called
    ``PLUGIN_CONFIG_CLASS()`` and rejected the candidate with an opaque
    Pydantic string, one node downstream, before the tuner ever saw it. The
    operator therefore never read the task's named refusal — the reachability
    the whole repair exists to restore.

    ``"PLUGIN_CONFIG_CLASS() must succeed with zero arguments"`` is not a
    valid generic validator invariant. The valid one is *"a probe states the
    values it needs"*, and it is declared once, in the Step-04 recipe module
    (``agent/skills/model_io_probe_skill.py``) — whose own docstring already
    names two copies of a probe recipe as the silent-divergence hazard this
    class pins shut.
    """

    #: Production trees a second copy could plausibly be written into.
    _PRODUCTION_TREES = (
        "src/agent",
        "src/core",
        "src/execute_tools",
        "src/ml_models",
        "src/nodes",
        "scripts",
        "src/workflows",
    )

    def test_the_rule_is_defined_exactly_once_in_production(self):
        """DEFECT THIS TEST ALONE CATCHES

            A SECOND authority. The failure mode is not a crash: a node that
            keeps (or re-grows) its own copy stays green in its own tests and
            diverges from the other node only for the candidates neither
            node's fixtures cover — which is how the implementor came to emit
            candidates the validator rejected in the first place.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The count is not 1 and every defining file is named.
        """
        import ast
        from pathlib import Path

        repo_root = Path(__file__).resolve().parents[4]
        definitions: list[str] = []
        for tree in self._PRODUCTION_TREES:
            for path in sorted((repo_root / tree).rglob("*.py")):
                try:
                    parsed = ast.parse(path.read_text(encoding="utf-8"))
                except (OSError, SyntaxError):  # pragma: no cover - unreadable file
                    continue
                for node in ast.walk(parsed):
                    if isinstance(node, ast.FunctionDef) and node.name == "probe_config_kwargs":
                        definitions.append(str(path.relative_to(repo_root)))

        assert definitions == ["src/agent/skills/model_io_probe_skill.py"], (
            "the probe's config-construction rule is defined somewhere other "
            f"than (or as well as) the Step-04 recipe module: {definitions}"
        )

    def test_both_probing_nodes_hold_the_same_function_object(self):
        """DEFECT THIS TEST ALONE CATCHES

            A node re-binding the name to a local re-implementation — a copy
            that the census above cannot see because it is spelled with a
            different ``def`` name and then aliased.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The identity comparison is False.
        """
        from agent.skills import model_io_probe_skill

        assert _impl.probe_config_kwargs is model_io_probe_skill.probe_config_kwargs
        assert _val.probe_config_kwargs is model_io_probe_skill.probe_config_kwargs

    def test_the_validators_instantiation_check_actually_calls_it(self, tmp_path, monkeypatch):
        """DEFECT THIS TEST ALONE CATCHES

            Check 6 bypassing the boundary — importing the authority while
            still constructing with ``PLUGIN_CONFIG_CLASS()``. Every other
            assertion here would stay green: the import exists, the object is
            shared, and the census counts one definition.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            No call is recorded, and the check's own error string (which
            names the Pydantic rejection) is printed alongside.
        """
        name = "c12p_f12e_g1_val_reach_v1"
        path = tmp_path / f"{name}.py"
        path.write_text(
            _impl._assemble_plugin(_implementor_input(name, {"channels": 8}), _CODE),
            encoding="utf-8",
        )

        seen: list[type] = []
        real = _val.probe_config_kwargs

        def _spy(config_cls):
            seen.append(config_cls)
            return real(config_cls)

        monkeypatch.setattr(_val, "probe_config_kwargs", _spy)

        inst_ok, _grad_ok, _otype_ok, err, _total, _trainable = (
            _val._check_instantiation_and_gradient(str(path))
        )

        assert seen, (
            "check 6 constructed the config class without asking the shared "
            f"probe authority (check reported: {err!r})"
        )
        assert (inst_ok, err) == (True, None)

    def test_the_probe_value_never_becomes_a_declaration(self, tmp_path, registered):
        """DEFECT THIS TEST ALONE CATCHES

            The repair re-introducing the very defect it removed, one layer
            down: a probe that writes its transient value onto the CLASS
            (a mutated ``model_fields`` default, a cached instance, a
            registry write-back). The number would then be read by
            ``resolve_model_field`` exactly as the old authored 40000 was,
            and the task's named refusal would be defeated again — this time
            from the validator instead of the implementor.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            The resolution chain stops answering ``(0, None)`` after a probe
            has run, and the observed pair is printed.
        """
        name = "c12p_f12e_g1_no_leak_v1"
        src = registered(name, {"channels": 8})
        path = tmp_path / f"{name}_probe.py"
        path.write_text(src, encoding="utf-8")

        before = _resolution_chain(name)
        _val._check_instantiation_and_gradient(str(path))
        assert _impl._smoke_test_plugin(src, name, None) is None
        after = _resolution_chain(name)

        assert before == (0, None), f"the undeclared candidate did not start undeclared: {before}"
        assert after == (0, None), (
            f"a probe's transient construction value escaped into the declaration: {after}"
        )

    def test_the_authority_supplies_nothing_a_class_declares_for_itself(self):
        """DEFECT THIS TEST ALONE CATCHES

            The shared helper becoming a hidden default of its own — either
            by overriding a value the candidate DID declare, or by inventing
            a field the candidate never declared at all. Both would restore
            "the framework decides the geometry" in a new location.

        HOW IT FAILS WHEN THE BEHAVIOUR REGRESSES

            A non-empty mapping is returned for a class that needs nothing,
            and the mapping is printed.
        """
        from pydantic import BaseModel, Field

        from agent.skills.model_io_probe_skill import probe_config_kwargs

        class _Declares(BaseModel):
            segmentation_size: int = Field(default=144, ge=1)

        class _HasNoSuchField(BaseModel):
            channels: int = 8

        class _Requires(BaseModel):
            segmentation_size: int = Field(ge=1)

        assert probe_config_kwargs(_Declares) == {}
        assert probe_config_kwargs(_HasNoSuchField) == {}
        assert probe_config_kwargs(object()) == {}
        # Hardcoded: the probe's own symbolic extent, never a task-scale
        # number. 40000 here is the original defect wearing a new hat.
        assert probe_config_kwargs(_Requires) == {"segmentation_size": 64}
