# core/capability_registry.py
"""
Unified discovery layer for agent-generated capabilities (losses today; models /
data-analysis tools / feature extractors in future).

A "capability" is anything the agent generates at runtime that subsequent
iterations may want to discover and reuse. The first concrete type is a custom
loss function (see ``ml_models.loss_plugin_loader``). The registry is
type-agnostic by design: each entry carries a ``capability_type`` field, and
callers filter by it.

Storage: a flat JSON array at ``{library}/_capability_index.json``, where
``{library}`` is the resolved generated-library root
(``core.generated_library`` — arXiv P1; env-overridable, defaults to
``~/.siderius/generated_library``). The pre-P1 repo-checkout index at
``agent_generated/_capability_index.json`` stays READABLE as a fallback
when the resolved index does not exist yet, and its rows are carried into
the resolved index by the first write — the checkout file itself is never
written again. Reading requires **only** ``json.load`` — no Python import
of the plugin module is needed, so a future CLI (e.g. ``siderius
capabilities list``) can inspect the registry even when individual plugin
files are broken.

Writes are atomic via tmp-file rename — concurrent ``register()`` calls from
two processes do not corrupt the JSON. The rename pattern matches the
``_snapshot_task_config`` helper landed in ``enable_global_task_config`` T1b.

See ``docs/design/enable_loss_inventory.md`` § Commit L1 for the full design.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from core.layout import checkout_path

# LEGACY CHECKOUT index path: the repository's
# ``agent_generated/_capability_index.json``, computed from the repository
# root beside this package. arXiv P1: this is a READ-ONLY compatibility fallback — the
# default index lives in the resolved generated-library root
# (``core.generated_library.capability_index_path()``, resolved at
# CONSTRUCTION time so env changes and test monkeypatching take effect),
# and this legacy file is consulted only when a default-constructed
# registry finds no resolved index yet. It is never written.
_LEGACY_CHECKOUT_INDEX_PATH = checkout_path("agent_generated", "_capability_index.json")

# Supported capability types. Loss is the first concrete type. ``model`` is
# reserved for a future opt-in registration of agent-generated model plugins;
# ``tool`` is reserved for data-analysis / feature-extractor plugins that
# future modules may introduce.
CapabilityType = Literal["loss", "model", "tool"]


class CapabilityContractSnapshot(BaseModel):
    """Dependency-neutral, immutable evidence attached to a capability.

    Core owns only canonical serialization and digest integrity.  The layer
    that owns ``contract_kind`` interprets the payload.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    contract_kind: str = Field(min_length=1)
    contract_version: int = Field(ge=1)
    canonical_payload: str = Field(min_length=2)
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")

    @model_validator(mode="after")
    def _validate_canonical_payload_and_digest(self):
        try:
            payload = json.loads(self.canonical_payload)
        except (TypeError, json.JSONDecodeError) as exc:
            raise ValueError("canonical_payload must be valid JSON") from exc
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        if canonical != self.canonical_payload:
            raise ValueError("canonical_payload must use canonical JSON encoding")
        digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        if digest != self.sha256:
            raise ValueError("capability contract sha256 does not match canonical_payload")
        return self


class CapabilityMetadata(BaseModel):
    """One row in the capability registry.

    Carried as a Pydantic model so the JSON shape is validated on every
    ``register()`` call — a typo'd field name (e.g. ``filepath`` instead of
    ``file_path``) raises a ``ValidationError`` at write time, not at read
    time when downstream code tries to load the missing key.

    Fields:
        name: The plugin's ``PLUGIN_*_TYPE`` key (e.g. ``"snr_weighted_mse"``).
            Must be unique within a given ``capability_type``.
        capability_type: One of ``"loss"``, ``"model"``, ``"tool"``.
        file_path: Absolute path to the plugin's ``.py`` file.
        created_at: ISO-8601 UTC timestamp captured at registration time.
        source_iteration: Optional iteration label (e.g. ``"iter_014"``) the
            plugin was generated by. ``None`` for capabilities not produced
            inside the agent loop (test fixtures, hand-written plugins).
        description: One-line plain-English summary. Rendered into the
            proposer's ``{AVAILABLE_LOSSES}`` placeholder (L5).
    """

    name: str = Field(min_length=1, description="Plugin's unique identifier key.")
    capability_type: CapabilityType = Field(description="Category of capability.")
    file_path: str = Field(min_length=1, description="Absolute path to the .py file.")
    created_at: str = Field(min_length=1, description="ISO-8601 UTC timestamp.")
    source_iteration: str | None = Field(
        default=None,
        description="Iteration label the plugin was generated by; None for non-agent sources.",
    )
    description: str = Field(default="", description="One-line plain-English summary.")
    mathematical_definition: str = Field(
        default="",
        description=(
            "Precise mathematical formula or pseudocode from the originating "
            "``CustomLossSpec``. Rendered into the proposer's "
            "``{available_losses_block}`` (L6c) so the proposer can judge "
            "semantic similarity between an existing loss and a candidate "
            "Branch C without inferring the formula from the description "
            "alone. Default empty string preserves back-compat with pre-L6c "
            "registry entries that don't carry this field."
        ),
    )
    contract_snapshot: CapabilityContractSnapshot | None = Field(
        default=None,
        description="Immutable, versioned capability contract evidence; semantics are owner-defined.",
    )


class CapabilityRegistry:
    """Persistent registry of agent-generated capabilities.

    Backed by ``{library}/_capability_index.json`` in the resolved
    generated-library root (arXiv P1). Each instance reads that file on
    demand (no in-memory cache) so concurrent processes see each other's
    writes via the filesystem.

    Legacy compatibility: a DEFAULT-constructed registry whose resolved
    index does not exist yet falls back to READING the pre-P1 repo-checkout
    index (``_LEGACY_CHECKOUT_INDEX_PATH``). Writes always target the
    resolved index — the first read-modify-write therefore carries the
    legacy rows forward, and the checkout file is never touched again.

    The registry is small (one row per ever-generated plugin, typically tens
    to low hundreds) so a full re-read per call is cheap. If profiling later
    shows this as a hot path, the caller can drop in a session-level cache.
    """

    def __init__(self, index_path: str | None = None) -> None:
        """Initialize with the index file path (defaults to the resolved one).

        Args:
            index_path: Optional override. When ``None`` (production
                default), resolves ``core.generated_library.
                capability_index_path()`` at construction time and enables
                the legacy checkout READ fallback. An EXPLICIT path is
                exact — no fallback — so tests passing a ``tmp_path``
                location can never accidentally read the checkout index.
        """
        if index_path is not None:
            self._index_path = index_path
            self._legacy_read_path: str | None = None
        else:
            # Lazy import: the registry stays importable with only pydantic
            # available, and the env read happens per construction so test
            # monkeypatching and operator exports both take effect.
            from core.generated_library import (
                capability_index_path,
                generated_library_is_workspace_bound,
            )

            self._index_path = capability_index_path()
            self._legacy_read_path = (
                None if generated_library_is_workspace_bound() else _LEGACY_CHECKOUT_INDEX_PATH
            )

    @property
    def index_path(self) -> str:
        """Absolute path to the backing JSON file."""
        return self._index_path

    def _read_raw(self) -> list[dict]:
        """Return the raw list of dicts from the index file.

        Returns ``[]`` when the file does not exist (first-run behavior). When
        the file exists but is empty or contains ``null``, returns ``[]`` —
        either case is treated as "no capabilities yet" rather than a hard
        error so a freshly-created index doesn't need special-casing at every
        caller.

        arXiv P1 — legacy READ fallback: a default-constructed registry whose
        resolved index is MISSING reads the legacy checkout index instead
        (when that exists). An index that exists — even holding an empty
        list, e.g. after every row was pruned — is authoritative and
        suppresses the fallback: a pruned-empty resolved index must not
        resurrect legacy ghosts.
        """
        read_path = self._index_path
        if not os.path.isfile(read_path):
            if self._legacy_read_path is None or not os.path.isfile(self._legacy_read_path):
                return []
            read_path = self._legacy_read_path
        with open(read_path, encoding="utf-8") as f:
            raw = json.load(f)
        if raw is None:
            return []
        if not isinstance(raw, list):
            raise ValueError(
                f"{read_path}: expected a JSON array at top level, "
                f"got {type(raw).__name__}. The registry index has been "
                f"corrupted — restore from git or delete the file to reset."
            )
        return raw

    def _write_raw(self, entries: list[dict]) -> None:
        """Atomically write the list of entries to the index file.

        Uses tmp-file-then-rename so a concurrent reader never sees a
        partially-written JSON file. Same atomicity pattern as the T1b
        ``_snapshot_task_config`` helper.
        """
        os.makedirs(os.path.dirname(self._index_path) or ".", exist_ok=True)
        # delete=False so we keep ownership of the path past the with-block;
        # we explicitly close + rename + cleanup ourselves.
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=os.path.dirname(self._index_path),
            prefix=".capability_index_",
            suffix=".tmp",
            delete=False,
        ) as tmp:
            json.dump(entries, tmp, indent=2, sort_keys=False)
            tmp.write("\n")
            tmp_path = tmp.name
        os.replace(tmp_path, self._index_path)

    def list(self, capability_type: CapabilityType | None = None) -> list[CapabilityMetadata]:
        """Return all registered capabilities, optionally filtered by type.

        Args:
            capability_type: If provided, only entries with this type are
                returned. ``None`` (default) returns everything.

        Returns:
            List of validated ``CapabilityMetadata`` objects, in insertion
            order. Empty list when the registry is empty or no entries match
            the filter.

        Raises:
            pydantic.ValidationError: Propagated if any row in the index
                violates the schema. This protects callers from silent
                corruption — a hand-edited registry with a malformed row
                surfaces at list time, not when the row is later accessed.
        """
        rows = self._read_raw()
        out: list[CapabilityMetadata] = []
        for row in rows:
            meta = CapabilityMetadata.model_validate(row)
            if capability_type is None or meta.capability_type == capability_type:
                out.append(meta)
        return out

    def exists(self, name: str, capability_type: CapabilityType) -> bool:
        """Return True iff a capability with this (name, capability_type) is registered.

        Used by the implementor's L4 short-circuit path: when the proposer
        asks for a loss the registry already has, the implementor skips the
        LLM code-generation call entirely and reuses the existing plugin.
        """
        return any(meta.name == name for meta in self.list(capability_type=capability_type))

    def register(self, metadata: CapabilityMetadata) -> None:
        """Append a new capability to the registry.

        Rejects duplicates of the (name, capability_type) tuple — if a caller
        re-registers an existing plugin, that's a code bug (the L4
        short-circuit should have caught the re-use). Raising here makes the
        bug audible at write time.

        Args:
            metadata: Validated CapabilityMetadata instance.

        Raises:
            ValueError: If a capability with the same (name, capability_type)
                already exists in the registry.
        """
        if self.exists(metadata.name, metadata.capability_type):
            raise ValueError(
                f"Capability already registered: name={metadata.name!r}, "
                f"capability_type={metadata.capability_type!r}. The implementor "
                f"should short-circuit on registry-hit before calling register() — "
                f"this exception means the short-circuit was missed."
            )
        rows = self._read_raw()
        rows.append(metadata.model_dump())
        self._write_raw(rows)

    def replace(self, metadata: CapabilityMetadata) -> None:
        """Replace an existing capability entry in-place by (name, capability_type).

        L6c — companion to :meth:`register`. Used by the workflow's
        ``_promote_loss_to_global`` to update a loss entry's ``file_path``
        after the plugin has been copied from a workspace-scoped path to
        the stable global ``agent_generated/losses/`` location. Without
        this method the registry would keep pointing at an ephemeral
        per-attempt path that disappears once the workspace is cleaned.

        Atomicity: matches :meth:`register`'s tmp-file-then-rename via the
        shared ``_write_raw`` helper, so concurrent readers never see a
        partially-rewritten index.

        Args:
            metadata: Validated ``CapabilityMetadata`` instance whose
                ``(name, capability_type)`` identifies the row to replace.
                All other fields are overwritten from the new metadata.

        Raises:
            ValueError: When no capability with this ``(name, capability_type)``
                exists. Replace is strict — silently inserting on miss would
                mask caller bugs (e.g. typo'd name).
        """
        rows = self._read_raw()
        for i, row in enumerate(rows):
            if (
                row.get("name") == metadata.name
                and row.get("capability_type") == metadata.capability_type
            ):
                rows[i] = metadata.model_dump()
                self._write_raw(rows)
                return
        raise ValueError(
            f"Cannot replace: no capability with name={metadata.name!r}, "
            f"capability_type={metadata.capability_type!r} in the registry. "
            f"Use register() to add a new entry instead."
        )

    def remove(self, name: str, capability_type: CapabilityType | None = None) -> bool:
        """Remove a capability entry by ``(name, capability_type)``.

        Companion to :meth:`register` used by cleanup paths — the
        workflow-startup phantom sweep in
        ``workflows.model_exploration._cleanup_stale_registry_entries``
        removes entries whose ``file_path`` no longer resolves to a real
        file (a signal that the plugin was registered pre-validation and
        the validator later failed, or that the ``.py`` was garbage-
        collected with the workspace).

        Atomicity: same tmp-file-then-rename via ``_write_raw`` as
        :meth:`register` / :meth:`replace`, so concurrent readers never
        see a partially-rewritten index.

        Args:
            name: Registry entry name to remove.
            capability_type: Optional filter — when set, only removes a
                row matching BOTH ``name`` and ``capability_type``.
                ``None`` removes any row with the matching name
                regardless of type (rarely useful; kept symmetric with
                :meth:`list` / :meth:`exists`).

        Returns:
            ``True`` if a row was removed, ``False`` if no matching row
            existed. Returning ``False`` on miss (rather than raising)
            makes idempotent cleanup loops cleanly re-runnable.
        """
        rows = self._read_raw()
        for i, row in enumerate(rows):
            if row.get("name") != name:
                continue
            if capability_type is not None and row.get("capability_type") != capability_type:
                continue
            del rows[i]
            self._write_raw(rows)
            return True
        return False
