# agent/schemas/validator.py
"""
Input and output schemas for ml_code_validator_agent.

This node receives the full set of file paths written by ml_model_implementor,
verifies plugin interface compliance, runs the generated pytest test suite,
and checks that description.md is present and non-empty.
No LLM calls. Fully deterministic.
"""

from __future__ import annotations

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field

from agent.schemas.storage import StorageConfig, LocalStorageConfig


class ValidatorInput(BaseModel):
    """
    Input to ml_code_validator_agent.

    Populated via the ml_model_impl_to_ml_model_valid protocol,
    which maps the full ImplementorOutput → ValidatorInput.
    All file paths come directly from the implementor's output schema —
    the validator never reads from storage to discover them.
    """

    model_type: str = Field(
        description="The PLUGIN_MODEL_TYPE key to validate.",
    )
    model_file_path: str = Field(
        description="Absolute path to the plugin file written by ml_model_implementor.",
    )
    test_file_path: str = Field(
        description="Absolute path to the test file written by ml_model_implementor.",
    )
    description_file_path: str = Field(
        description="Absolute path to the description.md written by ml_model_implementor. "
                    "Validated to exist and be non-empty so result_interpretation_agent "
                    "can load it in subsequent iterations.",
    )
    config_fields: Dict[str, Any] = Field(
        description="Config field names and their default values, as generated by the LLM. "
                    "Used to verify all fields are scalar types (int, float, bool) — "
                    "list or dict fields cannot be searched by the hyperparameter tuner.",
    )
    storage: StorageConfig = Field(
        default_factory=lambda: StorageConfig(
            backend="local",
            local=LocalStorageConfig(workspace="./siderius_workspace", run_name="v1"),
        ),
        description="Where this node writes its validation report "
                    "(e.g. validation_{run_name}.json).",
    )


class ValidatorOutput(BaseModel):
    """
    Output of ml_code_validator_agent.

    Consumed by tune_ml_hyperparam_agent via ml_model_valid_to_ml_model_tune
    to confirm the plugin is safe to use before starting a tuning run.
    """

    passed: bool = Field(
        description="True only if all checks pass: plugin loads, all pytest tests pass, "
                    "description.md exists and is non-empty, all config fields are scalar.",
    )
    model_type: str = Field(
        description="The model type key that was validated.",
    )
    plugin_registered: bool = Field(
        description="Whether the plugin file loaded successfully "
                    "(PLUGIN_MODEL_TYPE, PLUGIN_CONFIG_CLASS, PLUGIN_MODEL_CLASS all present).",
    )
    tests_passed: bool = Field(
        description="Whether all pytest tests in the generated test file passed.",
    )
    description_valid: bool = Field(
        description="Whether description.md exists and contains substantive content (>50 chars).",
    )
    config_fields_valid: bool = Field(
        description="Whether all config fields are scalar types (int, float, bool). "
                    "False if any field has a list, dict, or other container type.",
    )
    test_output: Optional[str] = Field(
        default=None,
        description="Full pytest stdout/stderr — captured on both pass and fail "
                    "for visibility into warnings and test details.",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Human-readable summary of what failed. None if passed=True.",
    )
