# agent/schemas/validator.py
"""
Input and output schemas for ml_code_validator_agent.

This node receives file paths and spec data from ml_model_implementor,
runs seven checks (four deterministic + one in-process + one gradient + one LLM review),
and emits a ValidatorOutput.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

from agent.schemas.hyperparam_tuning import ExpertAdviceInput
from agent.schemas.proposal import InheritedComponent

from agent.schemas.storage import StorageConfig, LocalStorageConfig


class LLMCodeReview(BaseModel):
    """Structured result of the LLM code review check."""

    spec_alignment: bool = Field(
        description="True if the implementation faithfully matches the mathematical definition.",
    )
    trainability_concerns: List[str] = Field(
        description="Concerns about gradient flow, training stability, or numerical issues. "
                    "Empty list if none.",
    )
    implementation_issues: List[str] = Field(
        description="Correctness bugs or logical errors found in the code. Empty list if none.",
    )
    passed: bool = Field(
        description="Trainability gate: True if the model will run and train without errors. "
                    "spec_alignment is assessed independently and does NOT affect this field — "
                    "a model can have spec_alignment=False and passed=True when it is a valid "
                    "trainable implementation that deviates in implementation details only.",
    )
    notes: str = Field(
        description="Brief overall assessment of the implementation quality.",
    )


class ValidatorInput(BaseModel):
    """
    Input to ml_code_validator_agent.

    Populated via the ml_model_impl_to_ml_model_valid protocol,
    which maps the full ImplementorOutput → ValidatorInput.
    All file paths and spec data come directly from the implementor's output schema.
    """

    model_type: str = Field(
        description="The PLUGIN_MODEL_TYPE key to validate.",
    )
    model_file_path: str = Field(
        description="Absolute path to the plugin file written by ml_model_implementor.",
    )
    test_file_path: str = Field(
        description="Absolute path to the test file written by ml_model_implementor.",
    )
    description_file_path: str = Field(
        description="Absolute path to the description.md written by ml_model_implementor.",
    )
    config_fields: Dict[str, Any] = Field(
        description="Config field names and their default values, as generated by the LLM. "
                    "Used to verify all fields are scalar types (int, float, bool).",
    )
    model_description: str = Field(
        description="Plain-English description of the architecture from the proposal. "
                    "Passed to the LLM reviewer so it can assess spec alignment.",
    )
    mathematical_definition: str = Field(
        description="Precise mathematical/architectural specification from the proposal. "
                    "Passed to the LLM reviewer to verify the implementation matches the spec.",
    )
    llm_provider: Literal["gemini", "openai"] = Field(
        default="gemini",
        description="LLM provider for the code review step.",
    )
    llm_model_id: str = Field(
        default="gemini-3.1-flash-lite-preview",
        description="Specific model ID passed to the provider for code review.",
    )
    expert_advice: ExpertAdviceInput = Field(
        default="",
        description="Structured guidance from upstream agents or orchestrators. "
                    "Accepts a plain string or a structured ExpertAdvice object.",
    )
    human_advice: Optional[str] = Field(
        default=None,
        description="Optional human-provided guidance (highest priority — overrides expert_advice). "
                    "When present, injected into the LLM prompt as high-priority context.",
    )
    inherited_components: List[InheritedComponent] = Field(
        default_factory=list,
        description="Claimed architectural primitives from the DiscoveryMemo. "
                    "When non-empty, the validator checks that each claimed "
                    "component's pattern appears in the plugin source code. "
                    "Empty list = check skipped (backward compat).",
    )
    storage: StorageConfig = Field(
        default_factory=lambda: StorageConfig(
            backend="local",
            local=LocalStorageConfig(workspace="./siderius_workspace", run_name="v1"),
        ),
        description="Where this node writes its validation report.",
    )


class ValidatorOutput(BaseModel):
    """
    Output of ml_code_validator_agent.

    Consumed by tune_ml_hyperparam_agent via ml_model_valid_to_ml_model_tune
    to confirm the plugin is safe to use before starting a tuning run.
    """

    passed: bool = Field(
        description="Trainability gate. True only if the model will run and train: plugin "
                    "loads, pytest passes, description valid, config fields scalar, in-process "
                    "instantiation succeeds, gradient flow confirmed, output type consistent, "
                    "and LLM review passes. Does NOT include inheritance_check_passed or "
                    "llm_review_spec_alignment — those are assessed independently and "
                    "propagated as deviation notes so the tuner can account for them without "
                    "blocking a trainable model on a fragile regex or a minor spec drift.",
    )
    model_type: str = Field(
        description="The model type key that was validated.",
    )
    plugin_registered: bool = Field(
        description="Whether the plugin file loaded and exposes PLUGIN_MODEL_TYPE, "
                    "PLUGIN_CONFIG_CLASS, PLUGIN_MODEL_CLASS.",
    )
    tests_passed: bool = Field(
        description="Whether all pytest tests in the generated test file passed.",
    )
    description_valid: bool = Field(
        description="Whether description.md exists and contains substantive content (>50 chars).",
    )
    config_fields_valid: bool = Field(
        description="Whether all config fields are scalar types (int, float, bool).",
    )
    instantiation_passed: bool = Field(
        description="Whether the model could be instantiated in-process and the forward pass "
                    "produced the correct output shape [1, 256, 64].",
    )
    gradient_check_passed: bool = Field(
        description="Whether a backward pass succeeded and all trainable parameters "
                    "received non-None gradients.",
    )
    output_type_valid: bool = Field(
        default=True,
        description="Whether PLUGIN_OUTPUT_TYPE matches the actual forward output dimensions. "
                    "'classifier' expects [B, 256, T], 'regressor' expects [B, T].",
    )
    llm_review_passed: bool = Field(
        description="Whether the LLM code review concluded the implementation is sound.",
    )
    inheritance_check_passed: bool = Field(
        default=True,
        description="Whether all claimed inherited_components were found in the plugin source. "
                    "True when inherited_components is empty (check skipped). "
                    "False when at least one claimed component's pattern was not found. "
                    "Informational only — does NOT affect `passed`. Regex-based checks are "
                    "brittle (e.g. 'encoder_decoder' fails on models that use F.interpolate "
                    "without the literal word). Unverified claims are surfaced to downstream "
                    "nodes via inheritance_deviation_notes and unverified_inherited_components.",
    )
    inheritance_check_notes: Optional[List[str]] = Field(
        default=None,
        description="Per-component results: which passed, which failed, which were skipped "
                    "(no pattern). None when inherited_components is empty.",
    )
    unverified_inherited_components: List[str] = Field(
        default_factory=list,
        description="Names of claimed inherited_components whose regex pattern did not match "
                    "the plugin source. Structured for downstream consumers (e.g. the "
                    "interpretation agent can avoid awarding confirmation credit for these "
                    "components). Empty when all claims verified or inherited_components is empty.",
    )
    test_output: Optional[str] = Field(
        default=None,
        description="Full pytest stdout/stderr captured on both pass and fail.",
    )
    llm_review_spec_alignment: Optional[bool] = Field(
        default=None,
        description="LLM assessment: does the implementation match the mathematical definition?",
    )
    llm_review_trainability_concerns: Optional[List[str]] = Field(
        default=None,
        description="LLM-identified concerns about gradient flow or training stability.",
    )
    llm_review_implementation_issues: Optional[List[str]] = Field(
        default=None,
        description="LLM-identified correctness bugs or logical errors.",
    )
    llm_review_notes: Optional[str] = Field(
        default=None,
        description="LLM's brief overall assessment of the implementation.",
    )
    spec_deviation_notes: Optional[str] = Field(
        default=None,
        description="Human-readable summary of how the implementation deviates from the "
                    "mathematical spec, when the model passes trainability checks but "
                    "spec_alignment=False. Propagated to the tuner's expert_advice so the "
                    "planner knows it is tuning an implementation that differs from the "
                    "proposed hypothesis. None when spec_alignment=True or when the model "
                    "failed validation entirely.",
    )
    inheritance_deviation_notes: Optional[str] = Field(
        default=None,
        description="Human-readable summary listing which claimed inherited_components could "
                    "not be verified in the plugin source, emitted when the model passes "
                    "trainability checks but inheritance_check_passed=False. Propagated to "
                    "the tuner's expert_advice so the planner knows some claimed primitives "
                    "may be absent or implemented differently than the regex expected. "
                    "None when inheritance_check_passed=True or when the model failed validation.",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Human-readable summary of what failed. None if passed=True.",
    )
