"""Explicit declarations and scoped bindings for two tuner pseudo witnesses."""

from __future__ import annotations

import json
import shutil
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import pytest
import yaml

from agent.schemas.hyperparam_tuning import HyperparamTuningInput
from execute_tools.task_registration_scope import run_registration_scope
from tests.helpers.composed_manifest import write_complete_manifest
from workflows.task_composition import (
    RunTaskComposition,
    bind_run_task_composition,
    build_task_composition_ref,
    compose_run_task_bindings,
)

ROOT = Path(__file__).resolve().parents[2]

_HEALTH_PROVIDER = '''"""Metadata-only fixture provider; execution is forbidden."""
from typing import Any, ClassVar
from execute_tools.health_checks._view_provider import HealthView
from execute_tools.health_checks.registry import register_view_provider
from execute_tools.health_checks.schemas import HealthCheckContext

class FixtureCategoricalProvider:
    provider_id: ClassVar[str] = "tuner_fixture_categories"
    capabilities: ClassVar[frozenset[str]] = frozenset({"categorical_predictions"})

    def materialize(self, capability_key: str, ctx: HealthCheckContext,
                    config: dict[str, Any] | None = None) -> HealthView:
        raise BaseException("Pseudo tuner must not materialize a Health view")

register_view_provider(FixtureCategoricalProvider())
'''


def _write_task_declarations(pack: Path, *, health: bool) -> None:
    """Replace Quickstart science with this fixture's own complete declarations."""
    profile = {
        "partition_count": 20,
        "anchor_selection_files": [4, 7, 9],
        "health_peek_files": [4, 7, 9],
        "topology": {
            "modality": "tabular",
            "partition_unit": "fixture_partition",
            "partition_domain": list(range(20)),
            "feature_dim": 4,
            "class_cardinality": 2,
            "rows_per_partition_per_leg": 8,
            "seed_when_omitted": 0,
            "sample_identity": ["leg", "partition", "row"],
            "legs": ["train", "eval"],
        },
    }
    (pack / "declared/dataset_profile.json").write_text(json.dumps(profile), encoding="utf-8")
    task_config = {
        "task_description": (
            "Orchestration-only binary-classification fixture. Each of 20 declared "
            "partitions has eight symbolic rows per distinct train/eval leg. "
            "Inputs are four float32 features and outputs are two class logits. "
            "No physical dataset or scientific result is generated by this fixture."
        ),
        "forward_contract": {
            "segmentation_applicability": "not_applicable",
            "model_io": {
                "input": {
                    "axes": [
                        {"role": "batch", "dimension": {"symbolic": "B"}},
                        {"dimension": {"fixed": 4}},
                    ],
                    "dtype": {"admissible": ["float32"]},
                },
                "output": {
                    "axes": [
                        {"role": "batch", "dimension": {"symbolic": "B"}},
                        {"role": "class", "dimension": {"fixed": 2}},
                    ],
                    "dtype": {"admissible": ["float32"]},
                },
            },
            "input_description": "four float32 features per symbolic row",
            "output_description": "two float32 class logits per symbolic row",
            "task_type": "classification",
            "output_head_note": "Return [B, 2] logits without softmax.",
            "task_note": "A supplied-outcome orchestration fixture, not a benchmark.",
        },
    }
    (pack / "declared/task_config.yaml").write_text(yaml.safe_dump(task_config), encoding="utf-8")
    if health:
        task_health = {
            "facts": {"encoding_family": "categorical_labels", "symbol_cardinality": 2},
            "health_peek_files": [],
            "plugins": [{"kind": "file", "ref": "../plugins/_fixture_health.py"}],
            "providers": [{"provider_id": "tuner_fixture_categories", "config": {}}],
            "roster": [
                {
                    "gate_id": "collapse",
                    "check": "categorical_dominant_fraction",
                    "disposition": "blocking",
                    "parameters": {"max_dominant_fraction": 0.9},
                    "reason": "Refuse a near-constant class in the supplied Health witness.",
                }
            ],
        }
        (pack / "plugins/_fixture_health.py").write_text(_HEALTH_PROVIDER, encoding="utf-8")
        (pack / "declared/task_health.yaml").write_text(
            yaml.safe_dump(task_health), encoding="utf-8"
        )


def make_tuner_composition(tmp_path: Path, *, health: bool = False) -> RunTaskComposition:
    """Compose a real temporary package; retain only the existing model/metric code."""
    shutil.copy(ROOT / "tests/fixtures/tuner_composed_task.py", tmp_path / "tuner_composed_task.py")
    manifest = write_complete_manifest(
        tmp_path,
        task_data_path={
            "file": "../../tuner_composed_task.py",
            "symbol": "TunerComposedTask",
            "id": "tuner_composed_rows",
        },
        objective={"config": {"loss_type": "ce", "reduction": "mean"}},
        task_health=(
            {"config": "../../examples/quickstart/declared/task_health.yaml"}
            if health
            else {"none": True}
        ),
        deliverable={"prefix": "tuner_fixture_predictions", "extension": ".json", "index_width": 4},
        interpretation_blocks={"none": True},
    )
    _write_task_declarations(tmp_path / "examples/quickstart", health=health)
    return compose_run_task_bindings(str(manifest))


def _write_policy(tmp_path: Path, *, observe: bool) -> str:
    """The selected policy file, not a fake result, owns the gate's action."""
    path = tmp_path / "fixture_health_policy.yaml"
    path.write_text(
        yaml.safe_dump(
            {
                "health_policy": {
                    "blocking": {
                        "gate_role": "blocking",
                        "after_round": "every",
                        "short_circuit": True,
                        "on_pass": "continue",
                        "on_fail": "continue" if observe else "invalidate_round",
                        "check_config": {"aggregation": "all_pass"},
                    }
                }
            }
        ),
        encoding="utf-8",
    )
    return str(path)


@contextmanager
def _isolated_registrations() -> Iterator[None]:
    """Preserve pre-existing model/Health state while this package is loaded."""
    from execute_tools.health_checks import _plugin_binding, config, registry
    from ml_models.models_format_sandbox import PLUGIN_CONFIG_REGISTRY
    from ml_models.models_sandbox import MODEL_REGISTRY
    from ml_models.plugin_loader import PLUGIN_OUTPUT_TYPE_REGISTRY

    mappings = (
        MODEL_REGISTRY,
        PLUGIN_CONFIG_REGISTRY,
        PLUGIN_OUTPUT_TYPE_REGISTRY,
        registry._REGISTRY,
        registry._PROVIDER_REGISTRY,
        _plugin_binding._VIEW_BINDINGS,
    )
    snapshots = [(mapping, dict(mapping)) for mapping in mappings]
    with pytest.MonkeyPatch.context() as scoped, run_registration_scope():
        scoped.setattr(_plugin_binding, "_RUN_SCOPE", None)
        scoped.setattr(_plugin_binding, "_TASK_FACTS", None)
        scoped.setattr(config, "_CACHED_GATES", None)
        scoped.setattr(config, "_CACHED_BINDING_IDENTITY", None)
        try:
            yield
        finally:
            for mapping, before in snapshots:
                mapping.clear()
                mapping.update(before)


@contextmanager
def composed_run(
    tmp_path: Path, agent_input: HyperparamTuningInput, *, health: bool = False
) -> Iterator[RunTaskComposition]:
    """Bind the actual task and policy with restoration on every exit path."""
    with _isolated_registrations():
        composition = make_tuner_composition(tmp_path, health=health)
        agent_input.task_composition_ref = build_task_composition_ref(composition)
        if health:
            agent_input.health_checks_config = _write_policy(
                tmp_path, observe=agent_input.healthgate_mode == "observe_only"
            )
        with bind_run_task_composition(composition, physical_data_root=str(tmp_path)):
            yield composition
